# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Running Jenkins Job!
  displayName: 'Jenkins Queue Job'

- task: JenkinsQueueJob@2
  inputs:
    serverEndpoint: 'JenkinsSC01_Test'
    jobName: 'sayeda-project1'
    captureConsole: true
    capturePipeline: true
    isParameterizedJob: false